### ISSUE TITLE
Circular import error on latest build

### ISSUE THREAD

**Issue by wildjames** [imayhaveborkedit/discord-ext-voice-recv#44]
Dependabot bumped from `0.4.2a145` to `0.5.0a167`, and now my test suite fails to run. The errors seems to be related to a circular import somewhere within the `voice-recv` module:
```
____________________________________________ ERROR collecting tests/test_discord_utils.py ____________________________________________
ImportError while importing test module '/workspaces/swearbot/tests/test_discord_utils.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/home/vscode/.local/share/uv/python/cpython-3.13.5-linux-x86_64-gnu/lib/python3.13/importlib/__init__.py:88: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
tests/test_discord_utils.py:4: in <module>
    from balaambot import discord_utils
src/balaambot/discord_utils.py:5: in <module>
    from balaambot.audio_handlers.multi_audio_source import MultiAudioSource, ensure_mixer
src/balaambot/audio_handlers/multi_audio_source.py:15: in <module>
    from balaambot.config import DISCORD_VOICE_CLIENT
src/balaambot/config.py:5: in <module>
    from discord.ext import voice_recv
/home/vscode/.venv/lib/python3.13/site-packages/discord/ext/voice_recv/__init__.py:11: in <module>
    from . import (
/home/vscode/.venv/lib/python3.13/site-packages/discord/ext/voice_recv/extras/__init__.py:3: in <module>
    from . import observer
E   ImportError: cannot import name 'observer' from partially initialized module 'discord.ext.voice_recv.extras' (most likely due to a circular import) (/home/vscode/.venv/lib/python3.13/site-packages/discord/ext/voice_recv/extras/__init__.py)
```

Note that this works fine with version `0.4.2a145`.

**Comment by imayhaveborkedit** [comment]
No its not circular thats just not supposed to be there (yet).  I'll fix it shortly.

**Comment by imayhaveborkedit** [comment]
Somehow the build process picked this up, all I need to do is push a new release to pypi.  This should be fixed now.
